/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Snake.ORA;
import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;


public class App extends Application {
    @Override
    public void start(Stage stage) {
      try {
        Parent root = FXMLLoader.load(getClass().getResource("/MainMenu.fxml"));
        Scene scene =  new Scene(root);
        stage.setScene(scene);
        stage.show();
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
        
        
    }

    public static void main(String[] args) {
        launch(args);
    }
}
